services:
  fitness_postgres:
    image: postgres:latest
    container_name: fitness_postgres
    environment:
      POSTGRES_USER: fitness
      POSTGRES_PASSWORD: fitness
      POSTGRES_DB: fitness_tracker_db
    ports:
      - "5432:5432"
    volumes:
      - fitness_postgres_data:/var/lib/postgresql
    networks:
      - fitness-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - fitness-network

  app:
    build: .
    container_name: fitness_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://fitness_postgres:5432/fitness_tracker_db
      SPRING_DATASOURCE_USERNAME: fitness
      SPRING_DATASOURCE_PASSWORD: fitness
    depends_on:
      - fitness_postgres
    networks:
      - fitness-network

volumes:
  fitness_postgres_data:
  minio_data:

networks:
  fitness-network:
    driver: bridge